name: Node.js package

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Clean install dependencies
        run: npm ci
      - name: Build test
        run: npm run build-test
      - name: Test
        run: npm test

  publish-gpr:
    name: Publish to GitHub Package Registry
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          registry-url: https://npm.pkg.github.com/
      - name: Clean install dependencies
        run: npm ci
      - run: npm config list
      - run: npm config list --json
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB}}

  publish-npm:
    name: Publish to npm
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment for GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - name: Clean install dependencies
        run: npm ci
      - run: npm config list
      - run: npm config list --json
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
