name: Node.js Package

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Clean install dependencies
        run: npm ci
      - name: Test
        run: npm test

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          registry-url: https://npm.pkg.github.com/
      - name: Clean install dependencies
        run: npm ci
      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB}}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
